#! /usr/bin/env dash

# COMP2041 Turnip - turnip-add command for the turnip assignment program
# turnip-add.sh
#
# This program was written by Taj Mace (z5691836) <taj.mace@unsw.edu.au>
# on 21/04/2026
#
# This command creates a new Turnip assignment
# It also created a new .turnip directory if it doesn't exist.

# ============================
# ----- helper functions -----
# ============================

# checks ONLY two arguments were given
validate_argument_count() {
    if [ "$1" -ne 2 ]; then
        echo "usage: turnip-add <assignment> <tests>" >&2
        exit 1
    fi
}

# checks filename corresponds to the following criteria:
# "Assignment names must start with a lowercase letter ([a-z]),
# and be followed only by letters, number and underscore ([a-zA-Z0-9_])"
validate_assignment_name() {
    if ! echo "$1" | grep -qE '^[a-z][a-zA-Z0-9_]*$'; then
        echo "turnip-add: invalid assignment: $1" >&2
        exit 1
    fi
}

# check for duplicate name
check_for_existing_assignment() {
    if [ -d ".turnip/$1" ]; then
	echo "turnip-add: assignment $1 already exists" >&2
	exit 1
    fi
}

# helper to run checks on given arguments
validate_arguments() {
    validate_argument_count "$#"
    validate_assignment_name "$1"
    check_for_existing_assignment "$1"
}

# checks given filepath contains a tar to extract
validate_tests_filepath() {
    if ! echo "$1" | grep -qE '^[a-zA-Z0-9_./-]+$'; then
        echo "turnip-add: invalid tests: $1" >&2
        exit 1
    fi
     
    if ! [ -f "$1" ]; then
        echo "turnip-add: $1: No such file or directory" >&2
        exit 1
    fi
}

# ========================
# ----- main script -----
# ========================
main() {
    validate_arguments "$@"

    assignment_name="$1"
    tests_filepath="$2"

    # create .turnip if needed
    if [ ! -d ".turnip" ]; then
        mkdir ".turnip"
        echo "directory .turnip created"
    fi

    validate_tests_filepath "$tests_filepath"
    tests_dir="./.turnip/$assignment_name/tests"
    mkdir -p "$tests_dir"

    # extract files from given path to new directory
    tar --extract --file="$tests_filepath" --directory="$tests_dir"
    echo "assignment $assignment_name created"
}

# ======================
# ----- run script -----
# ======================
main "$@"


